# Generated by Django 5.0.6 on 2024-06-13 18:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='StoreApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StoreApp.product')),
                ('colors', models.CharField(blank=True, max_length=255)),
                ('reviews', models.TextField(blank=True)),
                ('stock_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('item_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('similar_products', models.TextField(blank=True)),
                ('additional_images', models.ManyToManyField(blank=True, to='StoreApp.image')),
            ],
        ),
    ]
