# Generated by Django 5.0.6 on 2024-06-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='descriptions',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1999, on_delete=django.db.models.deletion.CASCADE, to='StoreApp.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='additionaldetail',
            name='colors',
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreApp.review'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='colors',
            field=models.ManyToManyField(blank=True, to='StoreApp.color'),
        ),
    ]
