# Generated by Django 5.0.6 on 2024-06-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_rename_screen_size_additionaldetail_ram_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldetail',
            name='similar_products',
        ),
    ]
