# Generated by Django 5.0.6 on 2024-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0007_remove_additionaldetail_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldetail',
            name='similar_products',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
