# Generated by Django 5.0.6 on 2024-06-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0008_additionaldetail_similar_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldetail',
            name='similar_products',
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_on', to='StoreApp.product'),
        ),
    ]
