# Generated by Django 5.0.6 on 2024-06-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0010_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
