# Generated by Django 5.0.6 on 2024-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0011_remove_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldetail',
            name='screen_size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
