# Generated by Django 5.0.6 on 2024-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='header',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
